# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/uni/ma_vfx/fx_anim/hadan/gui/hadan_new.ui'
#
# Created: Sun Feb 21 15:46:16 2016
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 307)
        self.lbl_logo = QtGui.QLabel(Dialog)
        self.lbl_logo.setGeometry(QtCore.QRect(10, 10, 240, 45))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.lbl_logo.setFont(font)
        self.lbl_logo.setObjectName("lbl_logo")
        self.btn_howToUse = QtGui.QPushButton(Dialog)
        self.btn_howToUse.setGeometry(QtCore.QRect(315, 22, 75, 23))
        self.btn_howToUse.setObjectName("btn_howToUse")
        self.ta_main = QtGui.QTabWidget(Dialog)
        self.ta_main.setGeometry(QtCore.QRect(10, 60, 381, 231))
        self.ta_main.setObjectName("ta_main")
        self.tp_settings = QtGui.QWidget()
        self.tp_settings.setObjectName("tp_settings")
        self.lbl_fractureType = QtGui.QLabel(self.tp_settings)
        self.lbl_fractureType.setGeometry(QtCore.QRect(10, 10, 79, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_fractureType.setFont(font)
        self.lbl_fractureType.setObjectName("lbl_fractureType")
        self.cb_fractureType = QtGui.QComboBox(self.tp_settings)
        self.cb_fractureType.setGeometry(QtCore.QRect(95, 7, 69, 22))
        self.cb_fractureType.setObjectName("cb_fractureType")
        self.cb_fractureType.addItem("")
        self.cb_fractureType.addItem("")
        self.cb_fractureType.addItem("")
        self.split_options = QtGui.QFrame(self.tp_settings)
        self.split_options.setGeometry(QtCore.QRect(70, 40, 301, 16))
        self.split_options.setFrameShape(QtGui.QFrame.HLine)
        self.split_options.setFrameShadow(QtGui.QFrame.Sunken)
        self.split_options.setObjectName("split_options")
        self.lbl_options = QtGui.QLabel(self.tp_settings)
        self.lbl_options.setGeometry(QtCore.QRect(10, 35, 55, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_options.setFont(font)
        self.lbl_options.setObjectName("lbl_options")
        self.lbl_uniform = QtGui.QLabel(self.tp_settings)
        self.lbl_uniform.setGeometry(QtCore.QRect(40, 65, 45, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_uniform.setFont(font)
        self.lbl_uniform.setObjectName("lbl_uniform")
        self.spin_uniform = QtGui.QSpinBox(self.tp_settings)
        self.spin_uniform.setGeometry(QtCore.QRect(90, 62, 81, 22))
        self.spin_uniform.setMaximum(999)
        self.spin_uniform.setObjectName("spin_uniform")
        self.spin_primary = QtGui.QSpinBox(self.tp_settings)
        self.spin_primary.setGeometry(QtCore.QRect(90, 90, 81, 22))
        self.spin_primary.setMaximum(999)
        self.spin_primary.setObjectName("spin_primary")
        self.lbl_primary = QtGui.QLabel(self.tp_settings)
        self.lbl_primary.setGeometry(QtCore.QRect(40, 93, 44, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_primary.setFont(font)
        self.lbl_primary.setObjectName("lbl_primary")
        self.spin_secondary = QtGui.QSpinBox(self.tp_settings)
        self.spin_secondary.setGeometry(QtCore.QRect(90, 120, 81, 22))
        self.spin_secondary.setMaximum(999)
        self.spin_secondary.setObjectName("spin_secondary")
        self.lbl_secondary = QtGui.QLabel(self.tp_settings)
        self.lbl_secondary.setGeometry(QtCore.QRect(25, 123, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_secondary.setFont(font)
        self.lbl_secondary.setObjectName("lbl_secondary")
        self.lbl_flux = QtGui.QLabel(self.tp_settings)
        self.lbl_flux.setGeometry(QtCore.QRect(192, 65, 23, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_flux.setFont(font)
        self.lbl_flux.setObjectName("lbl_flux")
        self.spin_flux = QtGui.QDoubleSpinBox(self.tp_settings)
        self.spin_flux.setGeometry(QtCore.QRect(220, 62, 81, 22))
        self.spin_flux.setObjectName("spin_flux")
        self.lbl_gap = QtGui.QLabel(self.tp_settings)
        self.lbl_gap.setGeometry(QtCore.QRect(193, 93, 22, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_gap.setFont(font)
        self.lbl_gap.setObjectName("lbl_gap")
        self.spin_gap = QtGui.QDoubleSpinBox(self.tp_settings)
        self.spin_gap.setGeometry(QtCore.QRect(220, 90, 81, 22))
        self.spin_gap.setObjectName("spin_gap")
        self.split_fracture = QtGui.QFrame(self.tp_settings)
        self.split_fracture.setGeometry(QtCore.QRect(10, 150, 355, 20))
        self.split_fracture.setFrameShape(QtGui.QFrame.HLine)
        self.split_fracture.setFrameShadow(QtGui.QFrame.Sunken)
        self.split_fracture.setObjectName("split_fracture")
        self.btn_fracture = QtGui.QPushButton(self.tp_settings)
        self.btn_fracture.setGeometry(QtCore.QRect(10, 170, 355, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_fracture.setFont(font)
        self.btn_fracture.setObjectName("btn_fracture")
        self.lbl_seed = QtGui.QLabel(self.tp_settings)
        self.lbl_seed.setGeometry(QtCore.QRect(185, 123, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_seed.setFont(font)
        self.lbl_seed.setObjectName("lbl_seed")
        self.spin_seed = QtGui.QSpinBox(self.tp_settings)
        self.spin_seed.setGeometry(QtCore.QRect(220, 120, 81, 22))
        self.spin_seed.setMaximum(999)
        self.spin_seed.setObjectName("spin_seed")
        self.ta_main.addTab(self.tp_settings, "")
        self.tp_positions = QtGui.QWidget()
        self.tp_positions.setObjectName("tp_positions")
        self.lv_positions = QtGui.QListWidget(self.tp_positions)
        self.lv_positions.setGeometry(QtCore.QRect(10, 10, 355, 161))
        self.lv_positions.setObjectName("lv_positions")
        self.btn_clear = QtGui.QPushButton(self.tp_positions)
        self.btn_clear.setGeometry(QtCore.QRect(324, 177, 41, 23))
        self.btn_clear.setObjectName("btn_clear")
        self.btn_remove = QtGui.QPushButton(self.tp_positions)
        self.btn_remove.setGeometry(QtCore.QRect(260, 177, 61, 23))
        self.btn_remove.setObjectName("btn_remove")
        self.btn_addSelected = QtGui.QPushButton(self.tp_positions)
        self.btn_addSelected.setGeometry(QtCore.QRect(10, 177, 81, 23))
        self.btn_addSelected.setObjectName("btn_addSelected")
        self.ta_main.addTab(self.tp_positions, "")
        self.tp_advanced = QtGui.QWidget()
        self.tp_advanced.setObjectName("tp_advanced")
        self.lbl_generatedCommand = QtGui.QLabel(self.tp_advanced)
        self.lbl_generatedCommand.setGeometry(QtCore.QRect(10, 10, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_generatedCommand.setFont(font)
        self.lbl_generatedCommand.setObjectName("lbl_generatedCommand")
        self.txt_generatedCommand = QtGui.QLineEdit(self.tp_advanced)
        self.txt_generatedCommand.setGeometry(QtCore.QRect(10, 30, 355, 20))
        self.txt_generatedCommand.setReadOnly(True)
        self.txt_generatedCommand.setPlaceholderText("")
        self.txt_generatedCommand.setObjectName("txt_generatedCommand")
        self.ta_main.addTab(self.tp_advanced, "")
        self.lbl_website = QtGui.QLabel(Dialog)
        self.lbl_website.setGeometry(QtCore.QRect(300, 290, 82, 13))
        self.lbl_website.setObjectName("lbl_website")

        self.retranslateUi(Dialog)
        self.ta_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_logo.setText(QtGui.QApplication.translate("Dialog", "The Logo Here", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_howToUse.setText(QtGui.QApplication.translate("Dialog", "How To Use?", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_fractureType.setText(QtGui.QApplication.translate("Dialog", "Fracture Type", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_fractureType.setItemText(0, QtGui.QApplication.translate("Dialog", "Uniform", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_fractureType.setItemText(1, QtGui.QApplication.translate("Dialog", "Cluster", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_fractureType.setItemText(2, QtGui.QApplication.translate("Dialog", "Bezier", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_options.setText(QtGui.QApplication.translate("Dialog", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_uniform.setText(QtGui.QApplication.translate("Dialog", "Uniform", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_primary.setText(QtGui.QApplication.translate("Dialog", "Primary", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_secondary.setText(QtGui.QApplication.translate("Dialog", "Secondary", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_flux.setText(QtGui.QApplication.translate("Dialog", "Flux", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_gap.setText(QtGui.QApplication.translate("Dialog", "Gap", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_fracture.setText(QtGui.QApplication.translate("Dialog", "Fracture", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_seed.setText(QtGui.QApplication.translate("Dialog", "Seed", None, QtGui.QApplication.UnicodeUTF8))
        self.ta_main.setTabText(self.ta_main.indexOf(self.tp_settings), QtGui.QApplication.translate("Dialog", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clear.setText(QtGui.QApplication.translate("Dialog", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_remove.setText(QtGui.QApplication.translate("Dialog", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_addSelected.setText(QtGui.QApplication.translate("Dialog", "Add Selected", None, QtGui.QApplication.UnicodeUTF8))
        self.ta_main.setTabText(self.ta_main.indexOf(self.tp_positions), QtGui.QApplication.translate("Dialog", "Positions", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_generatedCommand.setText(QtGui.QApplication.translate("Dialog", "Generated Command", None, QtGui.QApplication.UnicodeUTF8))
        self.ta_main.setTabText(self.ta_main.indexOf(self.tp_advanced), QtGui.QApplication.translate("Dialog", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_website.setText(QtGui.QApplication.translate("Dialog", "www.ngreen.org", None, QtGui.QApplication.UnicodeUTF8))

